// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NAJDeSwW6mnK729UFkclZcq7udObwXI',
    appId: '1:396171310401:web:e5eae49f0489373d8b1dc0',
    messagingSenderId: '396171310401',
    projectId: 'ev-chargers-27347',
    authDomain: 'ev-chargers-27347.firebaseapp.com',
    storageBucket: 'ev-chargers-27347.appspot.com',
    measurementId: 'G-P6H1LR5HFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1hAeWb0rkG1l431pQkALU4OG9BNUnKa0',
    appId: '1:396171310401:android:2061c4f2ad1b87558b1dc0',
    messagingSenderId: '396171310401',
    projectId: 'ev-chargers-27347',
    storageBucket: 'ev-chargers-27347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OA4pXkShnRcwhFNva_UhvJrrEE6ihnA',
    appId: '1:396171310401:ios:de0d53507a8b8fe58b1dc0',
    messagingSenderId: '396171310401',
    projectId: 'ev-chargers-27347',
    storageBucket: 'ev-chargers-27347.appspot.com',
    iosClientId:
        '396171310401-cspopenavrscb4kq7n5d2899sol6nevr.apps.googleusercontent.com',
    iosBundleId: 'com.example.evcharger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OA4pXkShnRcwhFNva_UhvJrrEE6ihnA',
    appId: '1:396171310401:ios:de0d53507a8b8fe58b1dc0',
    messagingSenderId: '396171310401',
    projectId: 'ev-chargers-27347',
    storageBucket: 'ev-chargers-27347.appspot.com',
    iosClientId:
        '396171310401-cspopenavrscb4kq7n5d2899sol6nevr.apps.googleusercontent.com',
    iosBundleId: 'com.example.evcharger',
  );
}
